/**
 * Generated by tsnapi — public API snapshot of `unplugin-macros/esbuild`
 */
// #region Variables
export declare const module.exports: typeof Macros.esbuild;
// #endregion

// #region Default Export
declare const _default: typeof Macros.esbuild;
export default _default
// #endregion