/**
 * Generated by tsnapi — public API snapshot of `unplugin-macros`
 */
// #region Interfaces
export interface MacroContext {
  id: string;
  source: string;
  emitFile: UnpluginBuildContext["emitFile"];
  ast: MacroAst;
  unpluginContext: UnpluginBuildContext & UnpluginContext;
}
export interface MacroRunner {
  init?: () => Thenable<void>;
  resolve: (_: string, _: string) => Thenable<string>;
  import: (_: string) => Thenable<Record<string, unknown>>;
  invalidate?: (_: string) => Thenable<Iterable<string> | undefined>;
  close?: () => Thenable<void>;
}
export interface NativeRunnerOptions {
  track?: boolean;
}
export interface Options {
  include?: FilterPattern;
  exclude?: FilterPattern;
  runner?: MacroRunner;
  enforce?: "pre" | "post" | undefined;
  attrs?: Record<string, string>;
  virtualModules?: boolean;
}
export interface TransformContext {
  id: string;
  s: RolldownString;
  unpluginContext: UnpluginBuildContext & UnpluginContext;
  deps: Map<string, Set<string>>;
  attrs: Record<string, string>;
  virtualModules?: Map<string, string>;
  getRunner: () => Promise<MacroRunner>;
}
// #endregion

// #region Types
export type UnrunRunnerOptions = Omit<Options, "path" | "preset">;
// #endregion

// #region Functions
export declare function defineMacro<Args extends any[], Return>(_: (this: MacroContext, ..._: Args) => Return): (..._: Args) => Return;
export declare function nativeRunner(_?: NativeRunnerOptions): MacroRunner;
export declare function resolveMacroPath(_: string, _: string): string;
export declare function resolveOptions(_: Options$1): OptionsResolved;
export declare function transformMacros(_: TransformContext): Promise<void>;
export declare function unrunRunner(_?: UnrunRunnerOptions): MacroRunner;
// #endregion

// #region Variables
export declare const Macros: UnpluginInstance<Options$1 | undefined, false>;
// #endregion