/**
 * Generated by tsnapi — public API snapshot of `unplugin-macros/rolldown`
 */
// #region Variables
export declare const module.exports: typeof Macros.rolldown;
// #endregion

// #region Default Export
declare const _default: typeof Macros.rolldown;
export default _default
// #endregion