/**
 * Generated by tsnapi — public API snapshot of `unplugin-macros/rollup`
 */
// #region Variables
export declare const module.exports: typeof Macros.rollup;
// #endregion

// #region Default Export
declare const _default: typeof Macros.rollup;
export default _default
// #endregion