/**
 * Generated by tsnapi — public API snapshot of `unplugin-macros/rspack`
 */
// #region Variables
export declare const module.exports: typeof Macros.rspack;
// #endregion

// #region Default Export
declare const _default: typeof Macros.rspack;
export default _default
// #endregion