/**
 * Generated by tsnapi — public API snapshot of `unplugin-macros/vite`
 */
// #region Variables
export declare const module.exports: typeof Macros.vite;
// #endregion

// #region Default Export
declare const _default: typeof Macros.vite;
export default _default
// #endregion