/**
 * Generated by tsnapi — public API snapshot of `unplugin-macros/webpack`
 */
// #region Variables
export declare const module.exports: typeof Macros.webpack;
// #endregion

// #region Default Export
declare const _default: typeof Macros.webpack;
export default _default
// #endregion